### ISSUE TITLE
Add svg processing to core

### ISSUE THREAD

**Issue by cferdinandi** [cferdinandi/kraken#122]
**Useful links:**
- http://css-tricks.com/svg-sprites-use-better-icon-fonts/
- https://www.npmjs.org/package/gulp-svgstore
- http://css-tricks.com/svg-use-external-source/

**Todo:**
- [x] Add SVG sprite generation
- [x] Add SVG styles
- [x] Add feature detection

``` js
return !!document.createElementNS && !!document.createElementNS('http://www.w3.org/2000/svg', 'svg').createSVGRect;
```
